### ISSUE TITLE
No protocols

### ISSUE THREAD

**Issue by DcShepherd** [I2PC/scipion-em-xmipptomo#114]
I recently did a git pull of scipion-em-xmipptomo and installed the updated plugin using "scipion3 installp -p scipion-em-xmipptomo --devel". The installation completed without errors, however, I do not see any of the xmipptomo protocols in the Scipion side bar or when I use the search tool. I tried uninstalling and reinstalling a previous commit but I have the same issue. 

I get this error when running any protocols 
> error when importing from xmipptomo.protocols: cannot import name 'XmippProtFlexAlign' from 'xmipp3.protocols' (/home/doulin/miniconda3/envs/scipion3/lib/python3.8/site-packages/xmipp3/protocols/__init__.py)
File "/home/doulin/clones/scipion-em-xmipptomo/xmipptomo/protocols/protocol_flexalign.py", line 29, in <module>
Check the plugin manager (Configuration->Plugins in Scipion manager window) or use 'scipion installp --help --checkUpdates' in the command line to check for upgrades,it could be a versions compatibility issue.

I checked the versions but nothing seems to work. Any suggestions on how to fix this issue would be greatly appreciated.

**Comment by albertmena** [comment]
Hi [DcShepherd](https://github.com/DcShepherd), 
We made changes in scipion-em-xmipp related to the protocol it warm _XmippProtFlexAlign_. Please update the xmipp repositories
`./xmipp git pull`
will update all the four repositories (xmipp, XmippCore, scipion-em-xmipp and xmippViz)

**Comment by DcShepherd** [comment]
Hello @albertmena thanks so much for your help, updating the repositories fixed the issue. However, I was not able to update the repositories using the './xmipp git pull' but I took a look at the xmipp script and updated the repositories manually.

**Comment by albertmena** [comment]
> Hello @albertmena thanks so much for your help, updating the repositories fixed the issue. However, I was not able to update the repositories using the `./xmipp git pull` but I took a look at the xmipp script and updated the repositories manually.

Maybe you were not in the path of Xmipp? anyway, glad to hear you can run xmippTomo.
