### ISSUE TITLE
Error with FlexAign processing EMPIAR 10164

### ISSUE THREAD

**Issue by fede-pe** [I2PC/scipion-em-xmipptomo#39]
I am getting this error constantly trying to process the movies from dataset EMPIAR 10164 with FlexAlign. The workflow is just importing the tilt series movies and running FlexAlign. The output error:

00046:   Benchmarking cuFFT ...
00047:   xmipp_cuda_movie_alignment_correlation: libraries/reconstruction/movie_alignment_correlation_base.cpp:229: MultidimArray<T> AProgMovieAlignmentCorrelation<T>::createLPF(T, const Dimensions&) [with T = float]: Assertion `Ts >= this->Ts' failed.
00048:   rank|placeness|type|data|X|Y|Z|batch|plan size estimate (MB)|plan size estimate 2 (MB)|plan size actual (MB)|data size (MB)|plan time (ms)|exec time (ms/signal)|exec time of batch (ms)|elements|performance (1k elem of signal/ms)|error message
00049:   many|out-of-place|R2R forward|float|9216|9216|1|1|324.0703125000|324.0703125000|324.0703125000|648.0703125000|4.5659999847|26.7392978668|26.7392978668|84934656|3176.3981933594|
00050:   Aborted (core dumped)
00051:   We cannot process /home/fede/DataSets/Empiar10164/data/frames/TS_01_001_3_0.mrc
00052:   Command 'xmipp_cuda_movie_alignment_correlation -i "Runs/088075_XmippProtTsFlexAlign/tmp/movie_000003/input_movie.xmd" -o "Runs/088075_XmippProtTsFlexAlign/extra/TS_01_001_3_0_shifts.xmd" --sampling 5.400000 --maxResForCorrelation 30.000000 --Bspline 3 --cropULCorner 0 0 --cropDRCorner 7419 7675 --outside wrap --frameRange 0 7  --frameRangeSum 0 7  --max_shift 30  --oavg "Runs/088075_XmippProtTsFlexAlign/extra/TS_01_00_03.mrc" --oavgInitial Runs/088075_XmippProtTsFlexAlign/tmp/movie_000003/initialMic.mrc --oaligned Runs/088075_XmippProtTsFlexAlign/extra/TS_01_001_3_0_aligned_movie.mrcs --minLocalRes 500.000000 --device 0 --processLocalShifts  --storage Runs/088075_XmippProtTsFlexAlign/extra/fftBenchmark.txt --controlPoints 3 3 4 --patchesAvg 3' returned non-zero exit status 134.
00053:   Traceback (most recent call last):
00054:     File "/home/fede/scipion3conda/scipion-pyworkflow/pyworkflow/protocol/protocol.py", line 187, in run
00055:       self._run()
00056:     File "/home/fede/scipion3conda/scipion-pyworkflow/pyworkflow/protocol/protocol.py", line 238, in _run
00057:       resultFiles = self._runFunc()
00058:     File "/home/fede/scipion3conda/scipion-pyworkflow/pyworkflow/protocol/protocol.py", line 234, in _runFunc
00059:       return self._func(*self._args)
00060:     File "/home/fede/scipion3conda/scipion-em-tomo/tomo/protocols/protocol_ts_correct_motion.py", line 157, in processTiltImageStep
00061:       raise Exception("Expected output file '%s' not produced!" % tiFn)
00062:   Exception: Expected output file 'Runs/088075_XmippProtTsFlexAlign/extra/TS_01_00_03.mrc' not produced!
00063:   Protocol failed: Expected output file 'Runs/088075_XmippProtTsFlexAlign/extra/TS_01_00_03.mrc' not produced!
00064:   FAILED: processTiltImageStep, step 3, time 2020-11-26 14:08:28.456146

As a possible hint, it may have something to do with the filename of the movies (it contains the angle separated with a dot, e.g. TS_01_001_3_0.mrc). I tried to fix this by changing the '.' character with '_' but, in the end, it got stuck with the same error in the second stack of movies, independently of the filename format.

**Comment by DStrelak** [comment]
Hi @fede-pe ,
send me please the command which is executed by scipion.
The issue seems to be one of the asserts I have there:
```00047: xmipp_cuda_movie_alignment_correlation: libraries/reconstruction/movie_alignment_correlation_base.cpp:229: MultidimArray AProgMovieAlignmentCorrelation::createLPF(T, const Dimensions&) [with T = float]: Assertion `Ts >= this->Ts' failed.```
Based on that, the issue seems somehow related to the Ts of the movie.

**Comment by fede-pe** [comment]
Here you have @DStrelak 

 xmipp_cuda_movie_alignment_correlation -i "Runs/088614_XmippProtTsFlexAlign/tmp/movie_000003/input_movie.xmd" -o "Runs/088614_XmippProtTsFlexAlign/extra/TS_01_001_3_0_shifts.xmd" --sampling 5.400000 --maxResForCorrelation 30.000000 --Bspline 3 --cropULCorner 0 0 --cropDRCorner 7419 7675 --outside wrap --frameRange 0 7  --frameRangeSum 0 7  --max_shift 30  --oavg "Runs/088614_XmippProtTsFlexAlign/extra/TS_01_00_03.mrc" --oavgInitial Runs/088614_XmippProtTsFlexAlign/tmp/movie_000003/initialMic.mrc --minLocalRes 500.000000 --device 0 --processLocalShifts  --storage Runs/088614_XmippProtTsFlexAlign/extra/fftBenchmark.txt --controlPoints 3 3 4 --patchesAvg 3

**Comment by DStrelak** [comment]
So the problem seems to be incompatible settings, namely sampling and maxResForCorrelation. The sampling rate is set wrongly for this dataset (should be 1.35 instead of 5.4). 
I have added an explicit check for these situations, together with a hint on how to resolve it (see https://github.com/I2PC/xmipp/pull/351)
